In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
df = pd.read_csv("data/health_indicators.csv")

df.head()

,country_code,country_name,region,income_level,year,population,population_growth,urban_pct,life_expectancy,life_expectancy_male,...,stunting_pct,wasting_pct,overweight_children_pct,undernourishment_pct,fertility_rate,adolescent_fertility,prenatal_care_pct,gdp_per_capita,gdp_per_capita_ppp,poverty_rate
0,ABW,Aruba,Latin America & Caribbean,High income,2000,90588.0,1.030817,65.354550,72.939,70.149,...,NaN,NaN,NaN,NaN,1.845,43.729,NaN,20681.023027,30245.706974,NaN
1,ABW,Aruba,Latin America & Caribbean,High income,2001,91439.0,0.935033,65.335114,73.044,70.251,...,NaN,NaN,NaN,NaN,1.813,40.463,NaN,20740.132583,31920.239073,NaN
2,ABW,Aruba,Latin America & Caribbean,High income,2002,92074.0,0.692052,65.282069,73.135,70.364,...,NaN,NaN,NaN,NaN,1.800,38.185,NaN,21307.248251,31888.508737,NaN
3,ABW,Aruba,Latin America & Caribbean,High income,2003,93128.0,1.138229,65.198292,73.236,70.488,...,NaN,NaN,NaN,NaN,1.808,37.807,NaN,21949.485996,32507.084315,NaN
4,ABW,Aruba,Latin America & Caribbean,High income,2004,95138.0,2.135358,65.088653,73.223,70.487,...,NaN,NaN,NaN,NaN,1.819,38.761,NaN,23700.631990,35059.273098,NaN

In [3]:
df.shape

(5275, 48)

In [4]:
df.describe()

,year,population,population_growth,urban_pct,life_expectancy,life_expectancy_male,life_expectancy_female,death_rate,birth_rate,health_expenditure_pct_gdp,...,stunting_pct,wasting_pct,overweight_children_pct,undernourishment_pct,fertility_rate,adolescent_fertility,prenatal_care_pct,gdp_per_capita,gdp_per_capita_ppp,poverty_rate
count,5275.000000,5.275000e+03,5274.000000,5275.000000,5275.000000,5275.000000,5275.000000,5275.000000,5275.000000,4514.000000,...,844.000000,843.000000,806.000000,3762.000000,5275.000000,5275.000000,741.000000,5110.000000,4838.000000,1827.000000
mean,2012.000000,3.378305e+07,1.280475,58.716732,70.748244,68.215760,73.394403,8.192702,21.095707,6.222646,...,24.009360,5.896679,6.198015,10.937400,2.797145,51.097317,86.791826,15749.091058,19781.847712,9.492118
std,7.211786,1.323408e+08,1.618914,23.674753,8.701547,8.471691,9.066795,3.412191,10.888048,2.867900,...,15.043393,4.401812,4.499476,11.043652,1.468998,42.893201,16.137098,25074.200336,22391.204701,17.142033
min,2000.000000,9.544000e+03,-11.356645,8.043814,14.665000,12.383000,20.006000,0.841000,4.200000,1.222602,...,0.500000,0.100000,0.000000,2.500000,0.721000,0.505000,16.100000,109.593814,403.983197,0.000000
25%,2006.000000,7.743870e+05,0.297465,39.060949,65.356000,62.722000,67.976000,6.033500,11.746000,4.126287,...,10.800000,2.400000,2.725000,2.500000,1.670000,15.427500,82.500000,1544.567936,3899.860735,0.300000
50%,2012.000000,5.943366e+06,1.175030,60.031069,72.442000,69.217000,75.689000,7.607000,18.172000,5.640688,...,23.800000,4.900000,5.300000,6.300000,2.274000,39.131000,92.800000,5356.365656,11309.514697,1.500000
75%,2018.000000,2.201484e+07,2.210221,77.627285,77.197000,74.500000,80.115000,9.780500,28.806500,7.966407,...,35.325000,8.700000,8.700000,15.600000,3.638500,75.234000,97.600000,20032.321089,28679.803239,9.800000
max,2024.000000,1.450936e+09,21.700343,100.000000,86.497000,84.560000,88.626000,72.483000,53.390000,27.089685,...,64.000000,24.600000,29.600000,72.500000,7.829000,206.357000,100.000000,288001.433369,180939.439450,94.900000

In [5]:
df.dtypes

country_code                      object
country_name                      object
region                            object
income_level                      object
year                               int64
population                       float64
population_growth                float64
urban_pct                        float64
life_expectancy                  float64
life_expectancy_male             float64
life_expectancy_female           float64
death_rate                       float64
birth_rate                       float64
health_expenditure_pct_gdp       float64
health_expenditure_per_capita    float64
physicians_per_1000              float64
hospital_beds_per_1000           float64
nurses_per_1000                  float64
under5_mortality                 float64
neonatal_mortality               float64
maternal_mortality               float64
tb_incidence                     float64
hiv_incidence                    float64
communicable_death_pct           float64
noncommunicable_death_pct        float64
smoking_male                     float64
smoking_female                   float64
obesity_pct                      float64
alcohol_per_capita               float64
diabetes_pct                     float64
safe_water_pct                   float64
sanitation_pct                   float64
handwashing_pct                  float64
immunization_measles             float64
immunization_dpt                 float64
immunization_bcg                 float64
immunization_pol3                float64
immunization_hib3                float64
stunting_pct                     float64
wasting_pct                      float64
overweight_children_pct          float64
undernourishment_pct             float64
fertility_rate                   float64
adolescent_fertility             float64
prenatal_care_pct                float64
gdp_per_capita                   float64
gdp_per_capita_ppp               float64
poverty_rate                     float64
dtype: object

In [6]:
df.isnull().sum()

country_code                        0
country_name                        0
region                              0
income_level                        0
year                                0
population                          0
population_growth                   1
urban_pct                           0
life_expectancy                     0
life_expectancy_male                0
life_expectancy_female              0
death_rate                          0
birth_rate                          0
health_expenditure_pct_gdp        761
health_expenditure_per_capita     764
physicians_per_1000              2444
hospital_beds_per_1000           2377
nurses_per_1000                  2443
under5_mortality                  425
neonatal_mortality                425
maternal_mortality                667
tb_incidence                      218
hiv_incidence                    1661
communicable_death_pct           4177
noncommunicable_death_pct        4177
smoking_male                     3971
smoking_female                   3971
obesity_pct                      5275
alcohol_per_capita               1405
diabetes_pct                     4855
safe_water_pct                   1684
sanitation_pct                   1806
handwashing_pct                  3494
immunization_measles              520
immunization_dpt                  520
immunization_bcg                 1393
immunization_pol3                 520
immunization_hib3                1542
stunting_pct                     4431
wasting_pct                      4432
overweight_children_pct          4469
undernourishment_pct             1513
fertility_rate                      0
adolescent_fertility                0
prenatal_care_pct                4534
gdp_per_capita                    165
gdp_per_capita_ppp                437
poverty_rate                     3448
dtype: int64

In [7]:
threshold = 0.5
df = df.loc[:, df.isnull().mean() < threshold]

In [8]:
# Numerical columns
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [9]:
# Categorical columns
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[num_cols] < (Q1 - 1.5 * IQR)) |
          (df[num_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [11]:
le = LabelEncoder()
df['country_name'] = le.fit_transform(df['country_name'])

In [12]:
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [13]:
df.isnull().sum()

country_code                     0
country_name                     0
region                           0
income_level                     0
year                             0
population                       0
population_growth                0
urban_pct                        0
life_expectancy                  0
life_expectancy_male             0
life_expectancy_female           0
death_rate                       0
birth_rate                       0
health_expenditure_pct_gdp       0
health_expenditure_per_capita    0
physicians_per_1000              0
hospital_beds_per_1000           0
nurses_per_1000                  0
under5_mortality                 0
neonatal_mortality               0
maternal_mortality               0
tb_incidence                     0
hiv_incidence                    0
alcohol_per_capita               0
safe_water_pct                   0
sanitation_pct                   0
immunization_measles             0
immunization_dpt                 0
immunization_bcg                 0
immunization_pol3                0
immunization_hib3                0
undernourishment_pct             0
fertility_rate                   0
adolescent_fertility             0
gdp_per_capita                   0
gdp_per_capita_ppp               0
dtype: int64

In [14]:
df.head()

,country_code,country_name,region,income_level,year,population,population_growth,urban_pct,life_expectancy,life_expectancy_male,...,immunization_measles,immunization_dpt,immunization_bcg,immunization_pol3,immunization_hib3,undernourishment_pct,fertility_rate,adolescent_fertility,gdp_per_capita,gdp_per_capita_ppp
0,ABW,7,Latin America & Caribbean,High income,-1.565632,-0.461653,0.110651,-0.032096,-0.242700,-0.254155,...,-0.017575,-0.12545,-0.171354,-0.077252,-0.158541,-0.147534,-0.563122,0.160286,0.610043,0.940060
1,ABW,7,Latin America & Caribbean,High income,-1.436803,-0.461564,0.038970,-0.032896,-0.219574,-0.231644,...,-0.017575,-0.12545,-0.171354,-0.077252,-0.158541,-0.147534,-0.597862,0.033786,0.615329,1.070654
2,ABW,7,Latin America & Caribbean,High income,-1.307975,-0.461498,-0.142867,-0.035078,-0.199532,-0.206705,...,-0.017575,-0.12545,-0.171354,-0.077252,-0.158541,-0.147534,-0.611975,-0.054446,0.666037,1.068180
3,ABW,7,Latin America & Caribbean,High income,-1.179147,-0.461388,0.191033,-0.038524,-0.177287,-0.179339,...,-0.017575,-0.12545,-0.171354,-0.077252,-0.158541,-0.147534,-0.603290,-0.069087,0.723462,1.116421
4,ABW,7,Latin America & Caribbean,High income,-1.050318,-0.461179,0.937243,-0.043033,-0.180151,-0.179560,...,-0.017575,-0.12545,-0.171354,-0.077252,-0.158541,-0.147534,-0.591348,-0.032136,0.880039,1.315463

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.to_csv("data/cleaned_health_indicators.csv", index=False)